"""Short about-paragraphs shown on Analyze this area cards."""

ABOUT: dict[str, str] = {
    # Hospitals
    "Apex Hospitals Borivali": "Apex is a 24/7 multi-speciality hospital on Chandavarkar Road, Borivali West, with casualty, ICU and cashless desks. It is a practical first stop for tourists staying around Borivali or Kandivali.",
    "Karuna Hospital Borivali": "Karuna is a charitable multi-speciality hospital in Jeevan Bima Nagar, Borivali East, run by the Mission Sisters of Ajmer. Casualty is 24/7; keep ID and a payment card ready.",
    "Shatabdi Hospital Borivali East": "BMC’s Shatabdi Hospital on Kasturba Cross Road, Borivali East, is the nearest public emergency hospital to Thakur Village. Go here first for trauma or if a private hospital quote is unclear.",
    "Oscar Hospital Kandivali": "Oscar Hospital sits in Mahavir Nagar, Kandivali West, with 24/7 casualty for the western suburb belt. Useful if you are on the Kandivali West / Link Road side of the pin.",
    "Namaha Hospital Kandivali": "Namaha Hospital is a local multi-speciality in Kandivali West with emergency and inpatient beds. It is closer than the big Andheri hospitals when you are around Mahavir Nagar or Charkop.",
    "Apex Super Speciality Kandivali": "Apex’s Kandivali / Charkop unit is a 24/7 super-speciality campus west of the Western Line. Ambulance and casualty run round the clock.",
    "Thunga Hospital Malad": "Thunga Hospital Malad (off S.V. Road near PVR Milap) is a 24/7 multi-speciality with ICU, OT and in-house pharmacy. It is the closest large private hospital south of Kandivali.",
    "Bhaktivedanta Hospital Mira Road": "Bhaktivedanta Hospital & Research Institute in Mira Road East is a large 24/7 tertiary centre for the Mira–Bhayandar belt, north of Borivali.",
    "Wockhardt Hospitals Mira Road": "Wockhardt Super Speciality at The Umrao IMSR, Mira Road, is a 350-bed 24/7 hospital with ICU, cath lab and emergency. Use it if you are north of Borivali.",
    "Nanavati Max Super Speciality": "Nanavati Max in Vile Parle West is a major tertiary hospital (casualty 24/7) for the airport / Juhu / Andheri belt.",
    "Lilavati Hospital & Research Centre": "Lilavati Hospital at Bandra Reclamation is a well-known private tertiary centre with 24/7 casualty. Best if you are already in Bandra / Mahim.",
    "Holy Family Hospital Bandra": "Holy Family Hospital on St. Andrew’s Road, Bandra West, is a 24/7 charitable multi-speciality with a busy emergency department.",
    "Bombay Hospital & Medical Research Centre": "Bombay Hospital at Marine Lines is a large central Mumbai tertiary hospital, a short hop from Churchgate and Marine Drive.",
    "INS Asvini Naval Hospital": "INHS Asvini in Colaba is the Indian Navy’s premier hospital. Civilian emergency access is limited; tourists should use Bombay Hospital or a private casualty unless directed here.",
    "Kokilaben Dhirubhai Ambani Hospital": "Kokilaben Hospital in Four Bungalows, Andheri West, is one of Mumbai’s largest private tertiary hospitals with a full 24/7 emergency.",
    "Holy Spirit Hospital Andheri East": "Holy Spirit Hospital in Andheri East is a long-running charitable multi-speciality with 24/7 casualty, useful on the WEH / airport-east side.",
    "Cooper Hospital Juhu": "HBT Medical College & Dr. R.N. Cooper Municipal Hospital in Juhu is the BMC emergency hospital for the Vile Parle–Juhu–Andheri West belt.",
    # Police
    "Kandivali Police Station": "Kandivali Police Station covers Kandivali East–West including Thakur Village. Dial 112 for emergencies; tourist helpline is 1363.",
    "Borivali Police Station": "Borivali Police Station is the local station for Borivali West/East and the SGNP approach. File a missing-property report here if something is stolen on the WR.",
    "Borivali East Police Chowky": "This chowky covers Borivali East / Thakur Village-side lanes closer to the college pin than the main Borivali West station.",
    "Andheri Police Station": "Andheri Police Station covers the busiest Western Line interchange. Use 112; keep the FIR / lost-property desk in mind after peak-hour thefts.",
    "Bandra Police Station": "Bandra Police Station covers Bandra West including Bandstand and Carter Road. Tourist-heavy; 112 and 1363 both work.",
    "Mira Road Police Station": "Covers Mira Road East and the hospital cluster north of Borivali. Dial 112.",
    "Marine Drive Police Control": "Marine Drive / Churchgate control is the tourist-facing desk for Queen’s Necklace and Nariman Point.",
    "Colaba Tourist Police Precinct": "Tourist Police at Colaba handle Gateway / Colaba Causeway complaints, touts and lost tourists. Helpline 1363.",
    "Azad Maidan Police Station (CST Area)": "Azad Maidan / Fort station covers CSMT and the heritage precinct. Useful after pickpocketing at the terminus.",
    "Vasai Police Station": "Local station for Vasai Road and the fort last-mile. Confirm auto fares; call 112 after dark isolated stretches.",
    "Virar Police Station": "Virar is the Western Line terminus precinct. Peak last-train crowding is the main tourist risk.",
    # Pharmacies
    "Wellness Forever Kandivali / Thakur Village": "24/7 chemist in Thakur Village / Kandivali East, a short walk from the college pin. Carry a prescription for antibiotics; OTC fever and ORS are usually available.",
    "Apollo Pharmacy Kandivali East": "Apollo Pharmacy in Kandivali East (Thakur Complex belt) stocks 24/7 medicines, baby care and basic first-aid.",
    "Wellness Forever Borivali": "Wellness Forever near Borivali station west is a reliable 24/7 chemist if the Thakur Village counter is closed or out of stock.",
    "Wellness Forever Mahavir Nagar": "24/7 Wellness Forever on the Kandivali West / Mahavir Nagar food-street side of the suburb.",
    "Apollo Pharmacy Borivali": "Apollo Pharmacy Borivali West for night refills when you are on the station-west side.",
    "Wellness Forever Churchgate": "24/7 chemist in the Churchgate office grid — useful before boarding a late Western Line.",
    "Apollo Pharmacy Fort / Churchgate": "Apollo Pharmacy on the Fort / Churchgate side, close to CSMT tourists.",
    "Wellness Forever Bandra": "24/7 chemist in Bandra West near Linking Road / Hill Road.",
    "Apollo Pharmacy Andheri": "Apollo Pharmacy at Andheri, the main interchange if you are transferring lines.",
    "Apollo Pharmacy Virar": "Night chemist at Virar West for the last-station belt.",
    "Wellness Forever 24x7 Chemist": "24/7 Wellness Forever chemist in South Mumbai (Churchgate).",
    "Apollo Pharmacy 24 Hours": "24-hour Apollo Pharmacy in the Fort precinct.",
    "Wellness Forever Malad": "24/7 chemist in Malad West, handy if you are between Kandivali and Goregaon.",
    # Grocery
    "Local kirana — Thakur Village": "Independent kirana and fruit stalls inside Thakur Village. Closest groceries to the college pin for water, snacks and SIM top-up; pay in cash or UPI.",
    "Star Bazaar Kandivali": "Star Bazaar hypermarket in Kandivali East — packaged food, water cases and toiletries a short cab from Thakur College.",
    "Reliance Smart Kandivali East": "Reliance Smart in Kandivali East for supermarket runs without going to Malad’s malls.",
    "DMart Kandivali West": "DMart at Mahavir Nagar / Kandivali West — cheapest bulk water and snacks; expect queues on Sundays.",
    "DMart Borivali": "DMart Borivali West hypermarket. Good for a full grocery restock if you are staying several days.",
    "DMart Infiniti Mall Malad": "DMart inside Infiniti Mall, Malad West — supermarket plus mall security, toilets and ATMs.",
    "DMart Mira Road": "DMart Mira Road for the northern WR suburbs.",
    "Reliance Smart Bandra": "Reliance Smart in Bandra for a quick supermarket stop near the station.",
    "Nature's Basket Churchgate / South": "Premium grocer in South Mumbai; imported snacks and bottled water near Churchgate hotels.",
    # Attractions
    "Thakur College Campus (TCET / Thakur Village)": "Thakur Educational Campus in Kandivali East is a well-lit residential-college pocket. Nearest WR stations are Kandivali and Borivali; prefer app cabs after 10 PM from the station.",
    "Sanjay Gandhi National Park Gate": "The main tourist gate of SGNP is in Borivali East. Enter only through the official ticket window, carry water, and leave forest trails before closing time.",
    "Kanheri Caves": "A cluster of Buddhist rock-cut caves inside SGNP. Combine with the park gate; last entry is enforced and isolated trails after dusk are not advised.",
    "Mandapeshwar Caves": "Small rock-cut caves near IC Colony, Borivali West. A short daylight heritage stop; not a late-evening site.",
    "Kandivali Station Precinct": "Kandivali WR station is the closest suburban rail gate to Thakur Village. East–west skywalk gets crowded in peak hours — keep phones zipped.",
    "Poinsur Gymkhana Grounds": "Neighbourhood sports ground and walking track on the Kandivali–Borivali east side. Safe in daylight with local families around.",
    "Gateway of India": "Mumbai’s waterfront arch at Apollo Bunder. Heavily patrolled; watch for touts offering fake boat tickets to Elephanta.",
    "Marine Drive Promenade": "The Queen’s Necklace seafront. Well lit and patrolled; stay off the sea wall in monsoon swell.",
    "Marine Drive Queen's Necklace": "Lit Marine Drive arc from Churchgate toward Malabar Hill. A preferred evening walk; keep valuables front-facing in crowds.",
    "Churchgate Station Precinct": "Western Line origin in the office district. Safe and well-patrolled, but crush-packed 8–10 AM and 6–9 PM.",
    "Bandra Fort & Bandstand": "Portuguese Castella de Aguada with Sea Link views. Stick to the lit Bandstand promenade after 10 PM.",
    "Bandra Fort & Sea Link Promenade": "Fort and Bandstand walk with views of the Bandra–Worli Sea Link. Evening crowds; keep to the promenade lighting.",
    "Juhu Beach": "Mumbai’s most famous suburban beach. Eat at marked stalls, watch belongings, and use metered or app autos back to Vile Parle / Andheri.",
    "Carter Road Promenade": "Bandra’s cafe sea-wall. Generally safe; phone snatches happen in dense weekend crowds.",
    "Global Vipassana Pagoda": "Golden pagoda on the Gorai peninsula. High-security, calm monument — reach via Borivali plus ferry or bus.",
    "Gorai Beach & Pagoda Access": "Gorai creek and beach used to reach the Pagoda. Ferries can pause in rough weather.",
    "Elephanta Caves Island": "UNESCO caves in the harbour. Boats leave from Gateway of India; last return boats are strict.",
    "Haji Ali Dargah": "Mosque-tomb on a causeway off Worli. Visit in daylight; the walkway floods at high tide.",
    "CSMT World Heritage Terminus": "UNESCO Victorian terminus and Central/Harbour hub. High security; watch bags on FOBs.",
    "Vasai Fort": "Large Portuguese seaside fort beyond Vasai Road station. Go in a group and return before last crowded locals.",
    "Aksa Beach": "Weekend beach west of Malad / Madh. Confirm auto fare; skip isolated stretches after dark.",
    "Upvan Lake & Yeoor Hills": "Lakeside garden on the Thane edge of SGNP. Daytime family spot.",
    "Central Park & Jewel of Navi Mumbai": "Large landscaped park in Kharghar, Navi Mumbai. Safe urban recreation, far from the Western Line pin.",
    # Hotels
    "Hotel Sai Palace Grand Borivali": "Practical 3-star walk from Borivali station west — a convenient base for SGNP and Thakur College.",
    "The Residence Hotel & Apartments Borivali": "Serviced stay in Borivali, about a short cab from Thakur Village. Useful if you want a kitchenette.",
    "Hotel Metro Palace Kandivali": "Budget-to-mid hotel near Kandivali station, the closest stay to Thakur College besides campus hostels.",
    "IBIS Mumbai Goregaon": "Reliable mid-scale Accor stay between Andheri and Borivali, 15–25 minutes to Thakur Village off-peak.",
    "The Fern Residency Goregaon": "4-star Goregaon East hotel with tourist-desk support; cab to Kandivali East in 20–25 minutes off-peak.",
    "Grand Sarovar Premiere Goregaon": "Full-service Goregaon hotel on the WEH side, a comfortable suburban base with easy WR access.",
    "The Taj Mahal Palace": "Heritage luxury hotel beside the Gateway of India. High security; short cab from Churchgate.",
    "Trident Hotel Nariman Point": "Marine Drive luxury stay with ocean views and a 24/7 concierge used to tourist questions.",
    "Taj Lands End": "Sea-facing Taj in Bandra West, next to Bandstand and the Sea Link views.",
    "The Orchid Hotel Mumbai Vile Parle": "Eco-luxury hotel beside the domestic airport and Juhu — a convenient Western Line / airport stopover.",
    "Ginger Mumbai Andheri": "Lean-luxe stay at Andheri, the busiest WR interchange. Use the subway with bags only in off-peak if you can.",
    "Keys Select Hotel Nestor Mumbai": "4-star Andheri East hotel with metro plus Western Line access toward Borivali.",
    # Food
    "Thakur Village Food Street": "Student food lane beside Thakur campus — frankie, Chinese bhel, juice. Busy and generally safe till about 11 PM.",
    "Aaswad Thakur Village": "Popular Maharashtrian / misal-pav style eatery in Thakur Village. Quick, cheap, and a short walk from the college gate.",
    "Sheetal Restaurant Thakur Village": "Casual multi-cuisine restaurant used by campus visitors for sit-down meals close to the pin.",
    "Mahavir Nagar Khau Galli": "Kandivali West’s famous night food street. Excellent chaat and sandwiches; keep wallets front-facing in the crush.",
    "Gokul Refreshment Borivali": "Long-running Gujarati / pav-bhaji favourite on the Borivali station-west side.",
    "Prakash Dabeli Kandivali": "Cult Kutchi dabeli counter in Kandivali West. Small shop, fast turnover, cash/UPI.",
    "Jai Hind Lunch Home": "Koli seafood institution on the Borivali / Kandivali belt — surmai, crab, sol kadhi.",
    "Bhagat Tarachand (Western Line)": "Reliable vegetarian thali chain with suburban outlets along the Western Line.",
    "Leopold Cafe & Bar": "Colaba heritage cafe since 1871. Tourist-heavy; keep bags on your lap.",
    "Bademiya Kebabs": "Late-night seekh and baida roti behind the Taj. Crowded, cash-friendly, and a Colaba ritual.",
    "Theobroma Churchgate": "Cafe-bakery at Churchgate for brownies and coffee before you board the WR.",
    "Cannon Pav Bhaji": "Iconic Fort / Churchgate pav bhaji. Evenings are packed; keep small notes ready.",
    "Elco Pani Puri Bandra": "Hill Road chaat institution. Busy, well-known, and a standard Bandra tourist stop.",
    "Carter Road Cafe Stretch": "Sea-wall cafes in Bandra. Prefer indoor seating after 11 PM.",
    "Mahesh Lunch Home Juhu": "Classic coastal seafood near Juhu Beach. Book ahead on weekends.",
    "Highway Gomantak": "Goan/Malvani seafood along the WEH (Andheri–Goregaon). Casual, popular with locals.",
    "Virar Beach Shacks": "End-of-line beach snacks at Virar. Return before the last crowded locals.",
    "Nalasopara Station Lane Eats": "Quick misal and vada pav at Nalasopara. Confirm auto fares (often non-meter).",
    "Candies Bandra": "All-day cafe in Pali / Bandra West. Tourist-friendly menus and card/UPI.",
    "Growel's 101 Mall": "Akurli Road mall in Kandivali East — multiplex, GameZone and supermarket. Closest full mall to Thakur Village.",
    "Infiniti Mall Malad": "Large Malad West mall on New Link Road with DMart, Timezone and multiplex.",
    "Inorbit Mall Malad": "Malad West Inorbit on Link Road. Family mall with cinema and food court.",
    "Oberoi Mall Goregaon": "Goregaon East mall beside the WEH and Mindspace office campus.",
    "GameZone Growel's 101": "Arcade inside Growel's 101, a short cab from Thakur College.",
    "Timezone Infiniti Mall Malad": "Timezone arcade inside Infiniti Mall Malad.",
    "Players Adda Thakur Village": "Local PlayStation / PC cafe in Thakur Village used by campus students.",
    "Mount Mary Church Bandra": "Hilltop basilica above Bandstand. September feast is crowded.",
    "ISKCON Juhu": "Large Juhu temple with prasadam and a well-managed visitor desk.",
    "Siddhivinayak Temple Dadar": "Famous Ganesh temple next to Dadar WR. Tuesday queues are dense.",
    "Versova Beach": "Fishing-village beach west of Andheri. Skip isolated stretches after dark.",
    "Linking Road Bandra": "Street-shopping spine from Khar to Bandra. Watch phones in the evening crush.",
}


def about_for(name: str, fallback: str | None, distance_km: float) -> str:
    body = ABOUT.get(name)
    if not body and fallback and len(fallback.strip()) > 50:
        body = fallback.strip()
    if not body:
        body = f"{name} is listed in this area’s safety and services directory."
    return f"{body} About {distance_km:.1f} km from your dropped pin."
