"""Extra Churchgate–Virar catalogue: zones, crimes, malls, gaming, sights, police.

Coordinates are public place centroids (stations, malls, hospitals) used as pins.
Crime rows are tourist-safety advisories, not a live FIR feed.
"""

# Larger radii so coloured belts read clearly on the live map.
ZONES = [
    dict(name="Marine Lines station precinct", risk_level="green", crime_rate=2.3,
         center_lat=18.9456, center_lng=72.8238, radius_meters=700,
         description="Office-and-hospital belt. Well patrolled; green for tourists by day."),
    dict(name="Charni Road / Girgaon Chowpatty", risk_level="yellow", crime_rate=4.8,
         center_lat=18.9516, center_lng=72.8186, radius_meters=650,
         description="Beach crowds and peak locals. Watch phones on the Chowpatty sand."),
    dict(name="Grant Road station crush", risk_level="yellow", crime_rate=5.5,
         center_lat=18.9634, center_lng=72.8158, radius_meters=550,
         description="Narrow exits and jewellery-market footfall. Bags front-facing in peak."),
    dict(name="Mumbai Central concourse", risk_level="red", crime_rate=7.9,
         center_lat=18.9696, center_lng=72.8194, radius_meters=600,
         description="Long-distance + suburban mix. High pickpocket reports on FOBs."),
    dict(name="Mahalaxmi / Haji Ali approach", risk_level="yellow", crime_rate=4.6,
         center_lat=18.9826, center_lng=72.8238, radius_meters=650,
         description="Causeway touts and high-tide flooding. Visit the dargah in daylight."),
    dict(name="Prabhadevi / Elphinstone FOB", risk_level="red", crime_rate=8.2,
         center_lat=19.0078, center_lng=72.8364, radius_meters=500,
         description="Historic FOB crush. Avoid hanging on doors; use inner coaches with bags."),
    dict(name="Matunga Road station", risk_level="yellow", crime_rate=5.1,
         center_lat=19.0272, center_lng=72.8461, radius_meters=500,
         description="Narrow platforms. Phone snatch risk when boarding Virar-side peak trains."),
    dict(name="Mahim station & Causeway", risk_level="yellow", crime_rate=5.0,
         center_lat=19.0410, center_lng=72.8402, radius_meters=550,
         description="Causeway traffic and station crush. Use the lit Mahim–Bandra stretch."),
    dict(name="Khar Road station", risk_level="yellow", crime_rate=4.9,
         center_lat=19.0698, center_lng=72.8374, radius_meters=500,
         description="Linking Road spillover crowds. Weekend phone-snatch caution."),
    dict(name="Pali Hill / Carter Road residential", risk_level="green", crime_rate=2.1,
         center_lat=19.0665, center_lng=72.8268, radius_meters=800,
         description="Lit cafe-and-promenade belt. Green; keep phones zipped in weekend density."),
    dict(name="Santacruz station west", risk_level="yellow", crime_rate=5.3,
         center_lat=19.0816, center_lng=72.8410, radius_meters=550,
         description="Airport-auto touts. Prefer app cabs to Juhu / domestic airport."),
    dict(name="Juhu scheme / ISKCON belt", risk_level="green", crime_rate=2.4,
         center_lat=19.1078, center_lng=72.8268, radius_meters=850,
         description="Hotel and temple pocket. Green by day; beach bags still get lifted."),
    dict(name="Vile Parle station", risk_level="yellow", crime_rate=5.4,
         center_lat=19.0993, center_lng=72.8441, radius_meters=550,
         description="Airport last-mile. Unmetered quotes to Juhu — insist meter or app cab."),
    dict(name="Lokhandwala / Versova", risk_level="yellow", crime_rate=4.4,
         center_lat=19.1368, center_lng=72.8264, radius_meters=800,
         description="Nightlife pocket. Green-yellow; stick to lit streets after 12 AM."),
    dict(name="Jogeshwari station", risk_level="yellow", crime_rate=5.6,
         center_lat=19.1364, center_lng=72.8486, radius_meters=550,
         description="WEH service-road last mile. Poor lighting on some east exits."),
    dict(name="Ram Mandir / Goregaon east yards", risk_level="yellow", crime_rate=5.0,
         center_lat=19.1516, center_lng=72.8502, radius_meters=550,
         description="Industrial-edge station. Use the official subway; skip isolated tracks."),
    dict(name="Goregaon station & Film City road", risk_level="yellow", crime_rate=5.2,
         center_lat=19.1646, center_lng=72.8494, radius_meters=650,
         description="Peak crush plus Film City taxi touts. App cab after 10 PM."),
    dict(name="Mindspace / Oberoi Mall Goregaon", risk_level="green", crime_rate=2.0,
         center_lat=19.1738, center_lng=72.8606, radius_meters=700,
         description="Mall and office campus with private security. Green for shoppers."),
    dict(name="Malad station east-west", risk_level="yellow", crime_rate=5.9,
         center_lat=19.1868, center_lng=72.8486, radius_meters=600,
         description="Infiniti / Inorbit last-mile crowding. Watch phones on the east FOB."),
    dict(name="Malad West malls & SV Road", risk_level="green", crime_rate=2.5,
         center_lat=19.1842, center_lng=72.8352, radius_meters=800,
         description="Infiniti and Inorbit security. Green inside malls; SV Road is busier."),
    dict(name="Mahavir Nagar / Charkop", risk_level="green", crime_rate=2.3,
         center_lat=19.2042, center_lng=72.8378, radius_meters=850,
         description="Residential Kandivali West. Green; lock two-wheelers at Khau Galli."),
    dict(name="Growel's 101 / Akurli Road", risk_level="green", crime_rate=2.2,
         center_lat=19.2034, center_lng=72.8722, radius_meters=700,
         description="Mall and school belt east of Kandivali. Green, well lit, family crowds."),
    dict(name="IC Colony / Borivali West residential", risk_level="green", crime_rate=2.0,
         center_lat=19.2374, center_lng=72.8496, radius_meters=800,
         description="Quiet residential lanes. Green in daylight; still lock parked bikes."),
    dict(name="Dahisar station", risk_level="yellow", crime_rate=5.5,
         center_lat=19.2574, center_lng=72.8680, radius_meters=600,
         description="Last Mumbai-corporation stop. Peak crowding toward Mira Road."),
    dict(name="Bhayandar station", risk_level="yellow", crime_rate=5.8,
         center_lat=19.3012, center_lng=72.8512, radius_meters=650,
         description="Creek-side suburb. Confirm auto fares; skip isolated west roads after 11 PM."),
    dict(name="Naigaon station", risk_level="yellow", crime_rate=5.4,
         center_lat=19.3512, center_lng=72.8464, radius_meters=550,
         description="Sparse last-mile lighting. Travel in groups if walking from the station."),
    dict(name="Nalasopara station", risk_level="yellow", crime_rate=6.0,
         center_lat=19.4194, center_lng=72.8178, radius_meters=600,
         description="Non-meter autos are common. Agree the fare before boarding."),
    # Widen the original corridor zones so they actually paint the map.
    dict(name="Churchgate–Nariman Point office grid", risk_level="green", crime_rate=2.4,
         center_lat=18.9322, center_lng=72.8264, radius_meters=800,
         description="Well-patrolled business district. Green for tourists by day and evening."),
    dict(name="Marine Drive promenade", risk_level="green", crime_rate=2.1,
         center_lat=18.9432, center_lng=72.8236, radius_meters=900,
         description="Lit seafront with regular patrols. Stay on the main walkway after midnight."),
    dict(name="Dadar station concourse & FOB", risk_level="red", crime_rate=8.4,
         center_lat=19.0186, center_lng=72.8440, radius_meters=700,
         description="Peak crush and bag-snatch reports on foot over-bridges. High tourist-crime density."),
    dict(name="Bandra Bandstand & Carter Road", risk_level="green", crime_rate=2.8,
         center_lat=19.0428, center_lng=72.8190, radius_meters=800,
         description="Popular promenade. Green overall; watch phones in weekend crowds."),
    dict(name="Bandra station west exit", risk_level="yellow", crime_rate=5.6,
         center_lat=19.0544, center_lng=72.8406, radius_meters=550,
         description="Taxi/auto overcharging and peak crowding. Use app cabs from the plaza."),
    dict(name="Andheri station & west subway", risk_level="red", crime_rate=8.1,
         center_lat=19.1197, center_lng=72.8468, radius_meters=700,
         description="Major interchange crush, pickpocketing and touts. Keep valuables front-facing."),
    dict(name="Goregaon–Malad WEH service road", risk_level="yellow", crime_rate=5.2,
         center_lat=19.1663, center_lng=72.8526, radius_meters=700,
         description="Fast traffic, poor pedestrian lighting in patches. Prefer cab after 10 PM."),
    dict(name="Thakur Village / Thakur College campus", risk_level="green", crime_rate=2.2,
         center_lat=19.21407, center_lng=72.8648, radius_meters=800,
         description="Residential-education pocket in Kandivali East. Green; well-lit campus roads."),
    dict(name="Kandivali station east-west skywalk", risk_level="yellow", crime_rate=5.8,
         center_lat=19.2045, center_lng=72.8513, radius_meters=550,
         description="Peak-hour crowding toward Thakur Village autos. Watch phones on skywalk."),
    dict(name="Borivali station auto stand", risk_level="yellow", crime_rate=6.1,
         center_lat=19.2307, center_lng=72.8567, radius_meters=650,
         description="SGNP / Gorai autos may quote flat fares. Insist meter or app cab."),
    dict(name="SGNP Borivali gate approach", risk_level="green", crime_rate=2.0,
         center_lat=19.2300, center_lng=72.8680, radius_meters=800,
         description="Official park approach. Green in daylight; leave trails before closing."),
    dict(name="Mira Road–Bhayandar creek belt", risk_level="yellow", crime_rate=5.4,
         center_lat=19.2813, center_lng=72.8758, radius_meters=800,
         description="Busy suburb. Yellow at isolated creek paths after dark."),
]

CRIMES = [
    ("Mumbai Central concourse", "Pickpocketing", "Mumbai Central FOB",
     "Wallets lifted on the suburban–long-distance overbridge in morning peak.", 18.9696, 72.8194),
    ("Prabhadevi / Elphinstone FOB", "Bag snatching", "Prabhadevi FOB",
     "Unattended backpacks taken in crush toward Parel / Dadar.", 19.0078, 72.8364),
    ("Matunga Road station", "Phone theft", "Matunga Road platform",
     "Phones snatched while boarding Virar-side peak locals.", 19.0272, 72.8461),
    ("Mahim station & Causeway", "Chain snatching", "Mahim Causeway signal",
     "Two-wheeler chain snatches reported at the causeway signals.", 19.0410, 72.8402),
    ("Khar Road station", "Phone theft", "Khar linking-road exit",
     "Weekend Linking Road spillover; phones taken from open pockets.", 19.0698, 72.8374),
    ("Santacruz station west", "Taxi touting", "Santacruz west taxi plaza",
     "Flat fares quoted to Juhu Beach and the domestic airport.", 19.0816, 72.8410),
    ("Vile Parle station", "Auto overcharging", "Vile Parle east auto stand",
     "Airport-bound autos refuse meter. Use prepaid or an app cab.", 19.0993, 72.8441),
    ("Juhu scheme / ISKCON belt", "Vendor overcharging", "Juhu Chowpatty stalls",
     "Casual beach photos billed as paid souvenirs.", 19.0988, 72.8263),
    ("Jogeshwari station", "Phone theft", "Jogeshwari east exit",
     "Peak crowding toward WEH; keep phones zipped on the stairs.", 19.1364, 72.8486),
    ("Goregaon station & Film City road", "Taxi touting", "Goregaon east taxi",
     "Film City / Aarey quotes without meter after 9 PM.", 19.1646, 72.8494),
    ("Malad station east-west", "Pickpocketing", "Malad east FOB",
     "Infiniti Mall last-mile crush; wallets taken at the ticket barrier.", 19.1868, 72.8486),
    ("Growel's 101 / Akurli Road", "Two-wheeler theft (parking)", "Growel's 101 parking",
     "Mall parking thefts of unlocked two-wheelers. Use the paid lot.", 19.2034, 72.8722),
    ("Mahavir Nagar / Charkop", "Two-wheeler theft (parking)", "Khau Galli parking",
     "Bikes lifted from unattended night-food parking. Use a disc lock.", 19.2040, 72.8420),
    ("Dahisar station", "Pickpocketing", "Dahisar platform 1",
     "Peak Virar locals; phones taken at the door.", 19.2574, 72.8680),
    ("Bhayandar station", "Auto overcharging", "Bhayandar west stand",
     "Creek-side autos quote flat fares after the last fast.", 19.3012, 72.8512),
    ("Nalasopara station", "Auto overcharging", "Nalasopara east",
     "Non-meter culture. Agree the fare before sitting down.", 19.4194, 72.8178),
    ("Charni Road / Girgaon Chowpatty", "Bag snatching", "Girgaon Chowpatty sand",
     "Beach bags left behind a stall get walked away with.", 18.9516, 72.8186),
    ("Lokhandwala / Versova", "Phone theft", "Lokhandwala circle",
     "Nightlife crowding; phones snatched from open tables.", 19.1368, 72.8264),
    ("Mindspace / Oberoi Mall Goregaon", "Parking theft", "Oberoi Mall basement",
     "Rare but reported two-wheeler lifts from the mall basement. Keep a disc lock.", 19.1738, 72.8606),
]

ATTRACTIONS = [
    dict(name="Growel's 101 Mall", region="Western Suburbs (Kandivali East)", category="Shopping Mall",
         rating=4.4, distance="1.5 km from Thakur College", safety_status="Mall security ✓",
         description="Akurli Road mall with multiplex, GameZone and supermarket. Closest full mall to Thakur Village.",
         website_url="https://www.growels101.com/", map_query="Growels+101+Kandivali"),
    dict(name="Raghuleela Mega Mall Kandivali", region="Western Suburbs (Kandivali West)", category="Shopping Mall",
         rating=4.2, distance="Kandivali West 2.4 km", safety_status="Mall security ✓",
         description="Kandivali West mall on the Poisar side with shops, food court and cinema.",
         website_url="https://www.google.com/maps/search/?api=1&query=Raghuleela+Mall+Kandivali",
         map_query="Raghuleela+Mall+Kandivali"),
    dict(name="Infiniti Mall Malad", region="Western Suburbs (Malad)", category="Shopping Mall",
         rating=4.5, distance="Malad West 1 km", safety_status="Mall security ✓",
         description="Large Malad West mall (New Link Road) with DMart, Timezone and multiplex. Private security.",
         website_url="https://www.infinitimall.com/", map_query="Infiniti+Mall+Malad"),
    dict(name="Inorbit Mall Malad", region="Western Suburbs (Malad)", category="Shopping Mall",
         rating=4.4, distance="Malad West 2 km", safety_status="Mall security ✓",
         description="Malad West Inorbit on Link Road. Family mall with cinema and food court.",
         website_url="https://www.inorbit.in/malad", map_query="Inorbit+Mall+Malad"),
    dict(name="Oberoi Mall Goregaon", region="Western Suburbs (Goregaon)", category="Shopping Mall",
         rating=4.5, distance="Goregaon East 1 km", safety_status="Mall security ✓",
         description="Goregaon East mall next to the Western Express Highway and Mindspace.",
         website_url="https://www.oberoimall.com/", map_query="Oberoi+Mall+Goregaon"),
    dict(name="Mega Mall Oshiwara", region="Western Suburbs (Andheri West)", category="Shopping Mall",
         rating=4.1, distance="Andheri / Oshiwara 2 km", safety_status="Mall security ✓",
         description="Oshiwara mall on the Andheri West Link Road. Cinema and high-street shops.",
         website_url="https://www.google.com/maps/search/?api=1&query=Mega+Mall+Oshiwara",
         map_query="Mega+Mall+Oshiwara+Andheri"),
    dict(name="Fun Republic Andheri", region="Western Suburbs (Andheri West)", category="Shopping Mall",
         rating=4.2, distance="Andheri West 1.5 km", safety_status="Mall security ✓",
         description="Andheri West multiplex-mall on New Link Road. Busy evenings, indoor security.",
         website_url="https://www.google.com/maps/search/?api=1&query=Fun+Republic+Andheri",
         map_query="Fun+Republic+Andheri"),
    dict(name="Moksh Plaza Borivali", region="Western Suburbs (Borivali)", category="Shopping Mall",
         rating=4.0, distance="Borivali West 0.8 km", safety_status="Mall security ✓",
         description="Neighbourhood plaza near Borivali station west — shops, food and ATM.",
         website_url="https://www.google.com/maps/search/?api=1&query=Moksh+Plaza+Borivali",
         map_query="Moksh+Plaza+Borivali"),
    dict(name="Maxus Mall Bhayandar", region="Northern Suburbs (Bhayandar)", category="Shopping Mall",
         rating=4.1, distance="Bhayandar 1 km", safety_status="Mall security ✓",
         description="Main mall for the Mira–Bhayandar belt with multiplex and food court.",
         website_url="https://www.google.com/maps/search/?api=1&query=Maxus+Mall+Bhayandar",
         map_query="Maxus+Mall+Bhayandar"),
    dict(name="Timezone Infiniti Mall Malad", region="Western Suburbs (Malad)", category="Gaming Cafe",
         rating=4.3, distance="Malad West 1 km", safety_status="Indoor venue ✓",
         description="Timezone arcade inside Infiniti Mall Malad. Family gaming; mall security till close.",
         website_url="https://www.timezone.co.in/", map_query="Timezone+Infiniti+Mall+Malad"),
    dict(name="GameZone Growel's 101", region="Western Suburbs (Kandivali East)", category="Gaming Cafe",
         rating=4.2, distance="1.5 km from Thakur College", safety_status="Indoor venue ✓",
         description="Arcade and console gaming inside Growel's 101, Akurli Road — closest big game zone to Thakur Village.",
         website_url="https://www.growels101.com/", map_query="GameZone+Growels+101"),
    dict(name="Smaaash Andheri", region="Western Suburbs (Andheri West)", category="Gaming Cafe",
         rating=4.3, distance="Andheri West 2 km", safety_status="Indoor venue ✓",
         description="Smaaash indoor sports and VR at Andheri / Lokhandwala. Card payment, indoor security.",
         website_url="https://www.smaaash.in/", map_query="Smaaash+Andheri+Mumbai"),
    dict(name="Smaaash Malad", region="Western Suburbs (Malad)", category="Gaming Cafe",
         rating=4.2, distance="Malad West 1.2 km", safety_status="Indoor venue ✓",
         description="Smaaash at Malad for cricket simulators, bowling and VR. Inside a guarded complex.",
         website_url="https://www.smaaash.in/", map_query="Smaaash+Malad"),
    dict(name="Players Adda Thakur Village", region="Western Suburbs (Kandivali East)", category="Gaming Cafe",
         rating=4.1, distance="0.6 km from Thakur College", safety_status="Campus pocket ✓",
         description="Local PlayStation / PC cafe used by Thakur Village students. Cash and UPI; busy till late.",
         website_url="https://www.google.com/maps/search/?api=1&query=Playstation+cafe+Thakur+Village+Kandivali",
         map_query="Playstation+cafe+Thakur+Village"),
    dict(name="Mount Mary Church Bandra", region="Western Suburbs (Bandra)", category="Heritage Church",
         rating=4.7, distance="Bandra West 1.5 km", safety_status="Safe Zone ✓",
         description="Hilltop basilica above Bandstand. September feast is crowded; keep bags front-facing.",
         website_url="https://en.wikipedia.org/wiki/Basilica_of_Our_Lady_of_the_Mount,_Bandra",
         map_query="Mount+Mary+Church+Bandra"),
    dict(name="ISKCON Juhu", region="Western Suburbs (Juhu)", category="Temple",
         rating=4.6, distance="Vile Parle / Juhu 2 km", safety_status="Safe Zone ✓",
         description="Large Hare Krishna temple on Juhu. Footwear desk, vegetarian prasadam, well policed.",
         website_url="https://www.iskconmumbai.com/", map_query="ISKCON+Juhu"),
    dict(name="Siddhivinayak Temple Dadar", region="Western Suburbs (Dadar)", category="Temple",
         rating=4.7, distance="Dadar 0.8 km", safety_status="Peak crowding ✓",
         description="Famous Ganesh temple next to Dadar WR. Tuesday queues are dense — skip bags on the shoulder.",
         website_url="https://www.siddhivinayak.org/", map_query="Siddhivinayak+Temple+Dadar"),
    dict(name="Gilbert Hill Andheri", region="Western Suburbs (Andheri West)", category="Geological Monument",
         rating=4.2, distance="Andheri 1 km", safety_status="Daylight Visit ✓",
         description="66-million-year-old basalt monolith in Andheri West. Short daylight climb; not a night site.",
         website_url="https://en.wikipedia.org/wiki/Gilbert_Hill", map_query="Gilbert+Hill+Andheri"),
    dict(name="Mahakali Caves Andheri", region="Western Suburbs (Andheri East)", category="Heritage Caves",
         rating=4.3, distance="Andheri East 2.5 km", safety_status="Daylight Visit ✓",
         description="Buddhist rock-cut caves in Andheri East. Combine with WEH / metro; go before dusk.",
         website_url="https://en.wikipedia.org/wiki/Mahakali_Caves", map_query="Mahakali+Caves+Andheri"),
    dict(name="Versova Beach", region="Western Suburbs (Andheri West)", category="Beach",
         rating=4.0, distance="Andheri / Versova 3 km", safety_status="Daylight Visit ✓",
         description="Fishing village beach west of Andheri. Cleaner than Juhu in patches; skip isolated stretches after dark.",
         website_url="https://en.wikipedia.org/wiki/Versova,_Mumbai", map_query="Versova+Beach+Mumbai"),
    dict(name="EsselWorld & Water Kingdom", region="Northern Suburbs (Gorai)", category="Amusement Park",
         rating=4.2, distance="Borivali then Gorai ferry", safety_status="Ticketed venue ✓",
         description="Gorai amusement parks. Reach via Borivali + ferry/bus; last ferries are strict.",
         website_url="https://www.esselworld.in/", map_query="EsselWorld+Gorai"),
    dict(name="Film City Goregaon", region="Western Suburbs (Goregaon)", category="Film Studio Tour",
         rating=4.1, distance="Goregaon East 4 km", safety_status="Guided access ✓",
         description="Dadasaheb Phalke Chitranagari. Public access is limited to official tours — ignore roadside touts.",
         website_url="https://www.filmcitymumbai.org/", map_query="Film+City+Goregaon"),
    dict(name="Chhota Kashmir Aarey", region="Western Suburbs (Goregaon)", category="Picnic Garden",
         rating=4.2, distance="Goregaon East / Aarey 3 km", safety_status="Daylight Visit ✓",
         description="Lakeside garden inside Aarey Colony. Family picnic spot; leave before dusk.",
         website_url="https://en.wikipedia.org/wiki/Aarey_Milk_Colony", map_query="Chhota+Kashmir+Aarey"),
    dict(name="Linking Road Bandra", region="Western Suburbs (Bandra)", category="Shopping Street",
         rating=4.3, distance="Bandra 1 km", safety_status="Crowd caution ✓",
         description="Street-shopping spine from Khar to Bandra. Peak evening pickpocket risk in the crush.",
         website_url="https://en.wikipedia.org/wiki/Linking_Road", map_query="Linking+Road+Bandra"),
    dict(name="Mahim Dargah", region="Western Suburbs (Mahim)", category="Dargah",
         rating=4.5, distance="Mahim 0.6 km", safety_status="Safe Zone ✓",
         description="Makhdoom Ali Mahimi dargah on the causeway. Busy on Thursdays; keep to the lit courtyard.",
         website_url="https://en.wikipedia.org/wiki/Mahim_Dargah", map_query="Mahim+Dargah"),
]

POLICE = [
    ("Dadar Police Station", "112", "Dadar 0.5 km", "Dadar West", 19.0192, 72.8432),
    ("Khar Police Station", "112", "Khar 0.4 km", "Khar West", 19.0696, 72.8368),
    ("Santacruz Police Station", "112", "Santacruz 0.5 km", "Santacruz West", 19.0814, 72.8406),
    ("Vile Parle Police Station", "112", "Vile Parle 0.4 km", "Vile Parle West", 19.0990, 72.8442),
    ("Goregaon Police Station", "112", "Goregaon 0.6 km", "Goregaon West", 19.1662, 72.8488),
    ("Malad Police Station", "112", "Malad 0.5 km", "Malad West", 19.1862, 72.8476),
    ("Dahisar Police Station", "112", "Dahisar 0.5 km", "Dahisar East", 19.2572, 72.8676),
    ("Bhayandar Police Station", "112", "Bhayandar 0.6 km", "Bhayandar West", 19.3010, 72.8508),
    ("Nalasopara Police Station", "112", "Nalasopara 0.5 km", "Nalasopara West", 19.4192, 72.8174),
    ("Jogeshwari Police Station", "112", "Jogeshwari 0.5 km", "Jogeshwari West", 19.1362, 72.8482),
]

HOSPITALS = [
    ("SevenHills Hospital Andheri East", "+912267676767", "Andheri East 3 km", "Marol",
     "https://www.sevenhillshospital.com/", 19.1174, 72.8782),
    ("BSES MG Hospital Andheri", "+912226732000", "Andheri West 1.2 km", "Andheri West",
     "https://www.bsesmghospital.com/", 19.1198, 72.8446),
    ("Suchak Hospital Malad", "+912228801500", "Malad East 1 km", "Malad East",
     "https://www.google.com/maps/search/?api=1&query=Suchak+Hospital+Malad", 19.1872, 72.8526),
    ("SRV Hospital Goregaon", "+912267676000", "Goregaon 1.5 km", "Goregaon West",
     "https://www.srvhospital.com/", 19.1654, 72.8462),
    ("Lotus Multispeciality Mira Road", "+912228121111", "Mira Road 1 km", "Mira Road East",
     "https://www.google.com/maps/search/?api=1&query=Lotus+Hospital+Mira+Road", 19.2824, 72.8742),
]

COORDS = {
    "Growel's 101 Mall": (19.2034, 72.8722),
    "Raghuleela Mega Mall Kandivali": (19.2086, 72.8374),
    "Infiniti Mall Malad": (19.1845, 72.8346),
    "Inorbit Mall Malad": (19.1738, 72.8366),
    "Oberoi Mall Goregaon": (19.1739, 72.8606),
    "Mega Mall Oshiwara": (19.1496, 72.8322),
    "Fun Republic Andheri": (19.1366, 72.8356),
    "Moksh Plaza Borivali": (19.2372, 72.8546),
    "Maxus Mall Bhayandar": (19.3012, 72.8510),
    "Timezone Infiniti Mall Malad": (19.1846, 72.8348),
    "GameZone Growel's 101": (19.2035, 72.8724),
    "Smaaash Andheri": (19.1368, 72.8266),
    "Smaaash Malad": (19.1860, 72.8352),
    "Players Adda Thakur Village": (19.2132, 72.8664),
    "Mount Mary Church Bandra": (19.0466, 72.8224),
    "ISKCON Juhu": (19.1132, 72.8266),
    "Siddhivinayak Temple Dadar": (19.0169, 72.8303),
    "Gilbert Hill Andheri": (19.1206, 72.8406),
    "Mahakali Caves Andheri": (19.1306, 72.8736),
    "Versova Beach": (19.1350, 72.8110),
    "EsselWorld & Water Kingdom": (19.2322, 72.8056),
    "Film City Goregaon": (19.1620, 72.8870),
    "Chhota Kashmir Aarey": (19.1510, 72.8800),
    "Linking Road Bandra": (19.0596, 72.8340),
    "Mahim Dargah": (19.0420, 72.8400),
    "SevenHills Hospital Andheri East": (19.1174, 72.8782),
    "BSES MG Hospital Andheri": (19.1198, 72.8446),
    "Suchak Hospital Malad": (19.1872, 72.8526),
    "SRV Hospital Goregaon": (19.1654, 72.8462),
    "Lotus Multispeciality Mira Road": (19.2824, 72.8742),
    "Dadar Police Station": (19.0192, 72.8432),
    "Khar Police Station": (19.0696, 72.8368),
    "Santacruz Police Station": (19.0814, 72.8406),
    "Vile Parle Police Station": (19.0990, 72.8442),
    "Goregaon Police Station": (19.1662, 72.8488),
    "Malad Police Station": (19.1862, 72.8476),
    "Dahisar Police Station": (19.2572, 72.8676),
    "Bhayandar Police Station": (19.3010, 72.8508),
    "Nalasopara Police Station": (19.4192, 72.8174),
    "Jogeshwari Police Station": (19.1362, 72.8482),
}
